# Generated by Django 3.1.1 on 2020-09-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gooddelivery',
            old_name='delivered_by',
            new_name='created_by',
        ),
    ]
