# Generated by Django 3.1.1 on 2020-09-09 10:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('good_delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryCampain',
            new_name='DeliveryCampaign',
        ),
        migrations.RenameField(
            model_name='agreement',
            old_name='created',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='deliverycampaign',
            old_name='created',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='deliverypoint',
            old_name='campain',
            new_name='campaign',
        ),
        migrations.RenameField(
            model_name='deliverypoint',
            old_name='created',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='deliverypointgoodstock',
            old_name='created',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='deliverypointgoodstockidentifier',
            old_name='created',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='good',
            old_name='created',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='goodcategory',
            old_name='created',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='gooddelivery',
            old_name='created',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='gooddeliveryagreement',
            old_name='created',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='gooddeliveryattachment',
            old_name='created',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='operatordeliverypoint',
            old_name='created',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='userdeliverypoint',
            old_name='created',
            new_name='create',
        ),
        migrations.AlterUniqueTogether(
            name='userdeliverypoint',
            unique_together={('user', 'delivery_point')},
        ),
    ]
