# Generated by Django 3.1.1 on 2020-09-17 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0002_auto_20200917_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='gooddelivery',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveder_by', to='good_delivery.operatordeliverypoint'),
        ),
        migrations.AddField(
            model_name='gooddelivery',
            name='disabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disabled_by', to='good_delivery.operatordeliverypoint'),
        ),
        migrations.AddField(
            model_name='gooddelivery',
            name='returned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_to', to='good_delivery.operatordeliverypoint'),
        ),
        migrations.AlterField(
            model_name='gooddelivery',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to='good_delivery.operatordeliverypoint'),
        ),
    ]
