# Generated by Django 3.1.1 on 2020-09-17 11:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0003_auto_20200917_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=1023),
        ),
    ]
