# Generated by Django 3.1.1 on 2020-09-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0004_auto_20200917_1312'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deliverypointgoodstock',
            unique_together={('good', 'delivery_point')},
        ),
    ]
