# Generated by Django 3.1.1 on 2020-09-18 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0005_auto_20200918_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCampaignAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='good_delivery.agreement')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='good_delivery.deliverycampaign')),
            ],
            options={
                'verbose_name': 'Agreement consegna',
                'verbose_name_plural': 'Agreement consegne',
            },
        ),
        migrations.AlterModelOptions(
            name='userdeliverypoint',
            options={'verbose_name': 'Utente al punto di raccolta', 'verbose_name_plural': 'Utenti ai punti di raccolta'},
        ),
        migrations.AlterField(
            model_name='deliverypointgoodstock',
            name='max_number',
            field=models.IntegerField(default=0, help_text='0 for unlimited'),
        ),
        migrations.DeleteModel(
            name='GoodDeliveryAgreement',
        ),
    ]
