# Generated by Django 3.1.1 on 2020-09-18 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0006_auto_20200918_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverypointgoodstockidentifier',
            options={'verbose_name': 'Identificativo bene in stock', 'verbose_name_plural': 'Identificativi beni in stock'},
        ),
    ]
