# Generated by Django 3.1.1 on 2020-09-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0007_auto_20200918_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdeliverypoint',
            options={'verbose_name': 'Prenotazioni utenti', 'verbose_name_plural': 'Prenotazioni utenti'},
        ),
        migrations.AddField(
            model_name='deliverycampaign',
            name='note_operator',
            field=models.TextField(blank=True, help_text='Notes to operators', null=True),
        ),
        migrations.AddField(
            model_name='deliverycampaign',
            name='note_users',
            field=models.TextField(blank=True, help_text='Notes to users', null=True),
        ),
    ]
