# Generated by Django 3.1.1 on 2020-09-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0009_auto_20200919_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gooddelivery',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
