# Generated by Django 3.1.1 on 2020-09-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0010_auto_20200919_2029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDeliveryPoint',
        ),
    ]
