# Generated by Django 3.1.1 on 2020-09-21 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('good_delivery', '0011_delete_userdeliverypoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gooddelivery',
            name='created_by',
        ),
        migrations.AddField(
            model_name='gooddelivery',
            name='delivery_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='good_delivery.deliverypoint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gooddelivery',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveder_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gooddelivery',
            name='delivered_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gooddelivery',
            name='disabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disabled_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gooddelivery',
            name='returned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
