# Generated by Django 3.1.1 on 2020-09-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0012_auto_20200921_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycampaign',
            name='require_user_reservation',
            field=models.BooleanField(default=True),
        ),
    ]
