# Generated by Django 3.1.1 on 2020-09-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0014_deliverycampaign_new_delivery_if_disabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverycampaign',
            old_name='require_user_reservation',
            new_name='operator_can_create',
        ),
    ]
