# Generated by Django 3.1.1 on 2020-09-24 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0015_auto_20200922_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gooddelivery',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='good_delivery.deliverycampaign'),
        ),
    ]
