# Generated by Django 3.1.1 on 2020-09-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0016_auto_20200924_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='gooddelivery',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
