# Generated by Django 3.1.1 on 2020-09-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0017_gooddelivery_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatordeliverypoint',
            name='multi_tenant',
            field=models.BooleanField(default=False),
        ),
    ]
