# Generated by Django 3.1.1 on 2020-09-25 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('good_delivery', '0018_operatordeliverypoint_multi_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='gooddelivery',
            name='choosen_delivery_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='choosen_delivered_point', to='good_delivery.deliverypoint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gooddelivery',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gooddelivery',
            name='delivery_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivered_point', to='good_delivery.deliverypoint'),
        ),
    ]
