# Generated by Django 3.1.1 on 2020-09-28 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('good_delivery', '0021_auto_20200928_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gooddelivery',
            name='delivery_point',
        ),
        migrations.RemoveField(
            model_name='gooddelivery',
            name='good',
        ),
        migrations.RemoveField(
            model_name='gooddelivery',
            name='good_identifier',
        ),
        migrations.RemoveField(
            model_name='gooddelivery',
            name='good_stock_identifier',
        ),
        migrations.RemoveField(
            model_name='gooddelivery',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='gooddelivery',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='gooddelivery',
            name='returned_point',
        ),
        migrations.RemoveField(
            model_name='gooddelivery',
            name='returned_to',
        ),
        migrations.CreateModel(
            name='GoodDeliveryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('good_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Data di restituzione')),
                ('delivery_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivered_point', to='good_delivery.deliverypoint')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='good_delivery.good')),
                ('good_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='good_delivery.gooddelivery')),
                ('good_stock_identifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='good_delivery.deliverypointgoodstockidentifier')),
                ('returned_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_point', to='good_delivery.deliverypoint')),
                ('returned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returned_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oggetto consegnato',
                'verbose_name_plural': 'Oggetti consegnati',
            },
        ),
    ]
