# Generated by Django 3.1.1 on 2020-09-28 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0022_auto_20200928_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gooddeliveryitem',
            name='delivery_point',
        ),
        migrations.AddField(
            model_name='gooddelivery',
            name='delivery_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivered_point', to='good_delivery.deliverypoint'),
        ),
    ]
