# Generated by Django 3.1.1 on 2020-09-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0024_auto_20200929_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gooddelivery',
            old_name='num_documento',
            new_name='document_number',
        ),
        migrations.RenameField(
            model_name='gooddelivery',
            old_name='tipo_documento',
            new_name='document_type',
        ),
    ]
