# Generated by Django 3.1.1 on 2020-09-30 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0025_auto_20200929_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gooddelivery',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='good_delivery.deliverycampaign'),
            preserve_default=False,
        ),
    ]
