# Generated by Django 3.1.1 on 2020-09-30 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0026_auto_20200930_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycampaign',
            name='identity_document_required',
            field=models.BooleanField(default=False),
        ),
    ]
