# Generated by Django 3.1.1 on 2020-09-30 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0027_deliverycampaign_identity_document_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gooddelivery',
            old_name='document_number',
            new_name='document_id',
        ),
    ]
