# Generated by Django 3.1.1 on 2020-10-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0028_auto_20200930_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='gooddelivery',
            name='disable_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
