# Generated by Django 3.1.1 on 2020-10-01 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('good_delivery', '0029_gooddelivery_disable_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gooddeliveryitem',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_delivered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gooddeliveryitem',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data di consegna'),
        ),
        migrations.AddField(
            model_name='gooddeliveryitem',
            name='delivery_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_delivered_point', to='good_delivery.deliverypoint'),
        ),
    ]
