# Generated by Django 3.1.1 on 2020-10-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0030_auto_20201001_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='gooddeliveryitem',
            name='notes',
            field=models.TextField(blank=True, max_length=511, null=True),
        ),
    ]
