# Generated by Django 3.1.1 on 2020-10-06 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0031_gooddeliveryitem_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gooddeliveryitem',
            name='notes',
        ),
    ]
