# Generated by Django 3.1.1 on 2020-10-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0032_remove_gooddeliveryitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypointgoodstockidentifier',
            name='notes',
            field=models.TextField(blank=True, max_length=511, null=True),
        ),
    ]
