# Generated by Django 3.1.1 on 2020-10-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0033_deliverypointgoodstockidentifier_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='subject',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
