# Generated by Django 3.1.1 on 2020-11-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0036_auto_20201006_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='gooddelivery',
            name='address_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gooddelivery',
            name='address_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='gooddelivery',
            name='address_number',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='gooddelivery',
            name='address_road',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gooddelivery',
            name='address_state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='gooddelivery',
            name='address_zip_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
