# Generated by Django 3.1.1 on 2020-11-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0038_auto_20201117_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gooddelivery',
            name='address_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
