# Generated by Django 3.1.1 on 2020-11-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0039_auto_20201117_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='gooddelivery',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
