# Generated by Django 3.1.1 on 2021-10-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_delivery', '0043_auto_20210601_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycampaign',
            name='default_delivered_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
